name: QNNenv
dependencies:
  - python>=3.5
  - pip>=19
  - matplotlib
  - notebook
  - ipywidgets
  - rise
  - opencv
  - pytorch
  - torchvision
  - pip:
      - qiskit
      - qiskit-aer-gpu
      - torchsummary
      - keras
      - pylatexenc
      - pillow
      - watchlogs